import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/auth";
import { Milestone, MilestoneType, MilestoneStatus } from "@/types";
import { updateMilestoneStatus } from "@/lib/milestone-generator";

export async function GET(
    request: NextRequest,
    { params }: { params: { id: string } }
) {
    try {
        const session = await auth();

        if (!session?.user) {
            return NextResponse.json(
                { error: "Unauthorized" },
                { status: 401 }
            );
        }

        const applicationId = params.id;

        // TODO: Fetch milestones from database
        // const milestones = await db.milestones.findMany({
        //     where: { applicationId },
        //     orderBy: { order: 'asc' }
        // });

        // Mock data for now
        const milestones: Milestone[] = [];

        // Update milestone statuses based on current date
        const updatedMilestones = milestones.map(updateMilestoneStatus);

        return NextResponse.json({
            success: true,
            milestones: updatedMilestones,
        });

    } catch (error) {
        console.error("Error fetching milestones:", error);
        return NextResponse.json(
            { error: "Internal server error" },
            { status: 500 }
        );
    }
}

export async function POST(
    request: NextRequest,
    { params }: { params: { id: string } }
) {
    try {
        const session = await auth();

        if (!session?.user) {
            return NextResponse.json(
                { error: "Unauthorized" },
                { status: 401 }
            );
        }

        const applicationId = params.id;
        const body = await request.json();

        const {
            type,
            label,
            description,
            plannedDate,
            location,
            requirementsChecklist,
            notes,
        } = body;

        // Validate required fields
        if (!type || !label || !plannedDate) {
            return NextResponse.json(
                { error: "Missing required fields: type, label, plannedDate" },
                { status: 400 }
            );
        }

        // Create new milestone
        const newMilestone: Milestone = {
            id: `${applicationId}-custom-${Date.now()}`,
            applicationId,
            type: type as MilestoneType,
            label,
            description,
            plannedDate: new Date(plannedDate),
            createdAt: new Date(),
            status: "PENDING" as MilestoneStatus,
            location,
            requirementsChecklist,
            notes,
            isAutoGenerated: false,
            order: 99, // Custom milestones go at the end
        };

        // TODO: Save to database
        // await db.milestones.create(newMilestone);

        return NextResponse.json({
            success: true,
            milestone: newMilestone,
            message: "Milestone created successfully",
        });

    } catch (error) {
        console.error("Error creating milestone:", error);
        return NextResponse.json(
            { error: "Internal server error" },
            { status: 500 }
        );
    }
}
