export type User = {
    id: string;
    email: string;
    name: string;
    image?: string;
    createdAt: Date;
    updatedAt: Date;
};

export type VisaType =
    | "uk_global_talent"
    | "us_h1b"
    | "us_o1"
    | "canada_express_entry"
    | "australia_skilled"
    | "eu_blue_card"
    | "singapore_ep"
    | "uae_golden"
    | "nz_skilled"
    | "japan_hsp"
    | "germany_blue"
    | "netherlands_hsm"
    | "ireland_critical";

export type ApplicationStatus =
    | "INTAKE"
    | "STAGE_1"
    | "STAGE_2"
    | "COMPLETED"
    | "REJECTED";

export type ApplicationLifecycleStatus =
    
    | "DOCUMENTS_IN_PROGRESS"    
    | "READY_TO_SUBMIT"          

    | "SUBMITTED_WAITING"        
    | "UNDER_REVIEW"             
    | "ADDITIONAL_DOCS_REQUESTED" 
    | "BIOMETRIC_SCHEDULED"      
    | "INTERVIEW_SCHEDULED"      
    | "DECISION_PENDING"         

    | "APPROVED"                 
    | "REJECTED"                 
    | "WITHDRAWN";               

export type Application = {
    id: string;
    userId: string;
    visaType: VisaType;
    status: ApplicationStatus;  
    stage: 1 | 2;
    createdAt: Date;
    updatedAt: Date;
    deadlineStage1?: Date;
    deadlineStage2?: Date;
    isPausedAtStage1: boolean;

    lifecycleStatus: ApplicationLifecycleStatus;
    completionScore: number;           

    submittedAt?: Date;
    submissionMethod?: "MANUAL" | "INTEGRATED";
    portalReferenceNumber?: string;
    submissionNotes?: string;

    decisionAt?: Date;
    decisionType?: "APPROVED" | "REJECTED";
    decisionNotes?: string;
    expectedDecisionDate?: Date;

    userNotes?: string;
    lastStatusUpdate?: Date;
};

export type DocumentType =
    | "cv"
    | "letter_of_recommendation"
    | "passport_photo"
    | "cover_letter"
    | "passport"
    | "degree_certificate";

export type DocumentStatus = "PENDING" | "VALIDATING" | "APPROVED" | "REJECTED" | "WARNINGS";

export type Document = {
    id: string;
    applicationId: string;
    type: DocumentType;
    fileUrl: string;
    fileName: string;
    fileSize: number;
    uploadedAt: Date;
    status: DocumentStatus;
    validationReport?: ValidationReport;
};

export type ValidationReport = {
    documentId: string;
    status: "APPROVED" | "REJECTED" | "WARNINGS";
    issuesFound: ValidationIssue[];
    suggestions: string[];
    generatedAt: Date;
};

export type ValidationIssue = {
    severity: "CRITICAL" | "WARNING";
    issue: string;
    fix: string;
};

export type MilestoneType =
    | "DOCUMENTS_COMPLETE"
    | "SUBMISSION"
    | "ENDORSEMENT_REVIEW"
    | "BIOMETRIC_APPOINTMENT"
    | "INTERVIEW"
    | "DECISION"
    | "CUSTOM";

export type MilestoneStatus =
    | "PENDING"
    | "IN_PROGRESS"
    | "COMPLETED"
    | "OVERDUE"
    | "CANCELLED";

export interface Milestone {
    id: string;
    applicationId: string;
    type: MilestoneType;
    label: string;
    description?: string;

    plannedDate: Date;
    actualDate?: Date;
    createdAt: Date;

    status: MilestoneStatus;

    location?: string;           
    requirementsChecklist?: string[];
    notes?: string;

    isAutoGenerated: boolean;
    order: number;               
}

export interface NextAction {
    id: string;
    applicationId: string;
    title: string;
    description: string;
    actionType: "USER_ACTION" | "WAITING" | "INFORMATIONAL";
    priority: "HIGH" | "MEDIUM" | "LOW";
    dueDate?: Date;
    ctaLabel?: string;
    ctaAction?: string;          
    relatedMilestoneId?: string;
}
