export type User = {
    id: string;
    email: string;
    name: string;
    image?: string;
    createdAt: Date;
    updatedAt: Date;
};

export type VisaType =
    | "uk_global_talent"
    | "us_h1b"
    | "us_o1"
    | "canada_express_entry"
    | "australia_skilled"
    | "eu_blue_card"
    | "singapore_ep"
    | "uae_golden"
    | "nz_skilled"
    | "japan_hsp"
    | "germany_blue"
    | "netherlands_hsm"
    | "ireland_critical";

// Legacy status (keep for backward compatibility)
export type ApplicationStatus =
    | "INTAKE"
    | "STAGE_1"
    | "STAGE_2"
    | "COMPLETED"
    | "REJECTED";

// NEW: Comprehensive application lifecycle states
export type ApplicationLifecycleStatus =
    // Pre-submission
    | "DOCUMENTS_IN_PROGRESS"    // score < 100%
    | "READY_TO_SUBMIT"          // score = 100%, not submitted

    // Post-submission
    | "SUBMITTED_WAITING"        // submitted, awaiting review
    | "UNDER_REVIEW"             // actively being reviewed
    | "ADDITIONAL_DOCS_REQUESTED" // authority needs more docs
    | "BIOMETRIC_SCHEDULED"      // biometric appointment set
    | "INTERVIEW_SCHEDULED"      // interview appointment set
    | "DECISION_PENDING"         // final decision imminent

    // Terminal states
    | "APPROVED"                 // ✅ success
    | "REJECTED"                 // ❌ denied
    | "WITHDRAWN";               // user cancelled

export type Application = {
    id: string;
    userId: string;
    visaType: VisaType;
    status: ApplicationStatus;  // legacy
    stage: 1 | 2;
    createdAt: Date;
    updatedAt: Date;
    deadlineStage1?: Date;
    deadlineStage2?: Date;
    isPausedAtStage1: boolean;

    // NEW: Enhanced lifecycle management
    lifecycleStatus: ApplicationLifecycleStatus;
    completionScore: number;           // 0-100

    // NEW: Submission tracking
    submittedAt?: Date;
    submissionMethod?: "MANUAL" | "INTEGRATED";
    portalReferenceNumber?: string;
    submissionNotes?: string;

    // NEW: Decision tracking
    decisionAt?: Date;
    decisionType?: "APPROVED" | "REJECTED";
    decisionNotes?: string;
    expectedDecisionDate?: Date;

    // NEW: User notes
    userNotes?: string;
    lastStatusUpdate?: Date;
};

export type DocumentType =
    | "cv"
    | "letter_of_recommendation"
    | "passport_photo"
    | "cover_letter"
    | "passport"
    | "degree_certificate";

export type DocumentStatus = "PENDING" | "VALIDATING" | "APPROVED" | "REJECTED" | "WARNINGS";

export type Document = {
    id: string;
    applicationId: string;
    type: DocumentType;
    fileUrl: string;
    fileName: string;
    fileSize: number;
    uploadedAt: Date;
    status: DocumentStatus;
    validationReport?: ValidationReport;
};

export type ValidationReport = {
    documentId: string;
    status: "APPROVED" | "REJECTED" | "WARNINGS";
    issuesFound: ValidationIssue[];
    suggestions: string[];
    generatedAt: Date;
};

export type ValidationIssue = {
    severity: "CRITICAL" | "WARNING";
    issue: string;
    fix: string;
};

// NEW: Milestone System
export type MilestoneType =
    | "DOCUMENTS_COMPLETE"
    | "SUBMISSION"
    | "ENDORSEMENT_REVIEW"
    | "BIOMETRIC_APPOINTMENT"
    | "INTERVIEW"
    | "DECISION"
    | "CUSTOM";

export type MilestoneStatus =
    | "PENDING"
    | "IN_PROGRESS"
    | "COMPLETED"
    | "OVERDUE"
    | "CANCELLED";

export interface Milestone {
    id: string;
    applicationId: string;
    type: MilestoneType;
    label: string;
    description?: string;

    // Dates
    plannedDate: Date;
    actualDate?: Date;
    createdAt: Date;

    // Status
    status: MilestoneStatus;

    // Additional data
    location?: string;           // for appointments
    requirementsChecklist?: string[];
    notes?: string;

    // Metadata
    isAutoGenerated: boolean;
    order: number;               // for sorting
}

// NEW: Next Action System
export interface NextAction {
    id: string;
    applicationId: string;
    title: string;
    description: string;
    actionType: "USER_ACTION" | "WAITING" | "INFORMATIONAL";
    priority: "HIGH" | "MEDIUM" | "LOW";
    dueDate?: Date;
    ctaLabel?: string;
    ctaAction?: string;          // e.g., "MARK_SUBMITTED", "UPLOAD_DOCS"
    relatedMilestoneId?: string;
}
