import { Milestone, MilestoneType, VisaType, ApplicationLifecycleStatus } from "@/types";

/**
 * Calculate expected decision date based on visa type
 * These are average processing times - actual times may vary
 */
export function calculateExpectedDecisionDate(
    visaType: VisaType,
    submittedAt: Date
): Date {
    const processingDays: Record<VisaType, number> = {
        uk_global_talent: 56,        // 8 weeks
        us_h1b: 90,                   // 3 months (regular processing)
        us_o1: 90,                    // 3 months
        canada_express_entry: 180,    // 6 months
        australia_skilled: 120,       // 4 months
        eu_blue_card: 90,             // 3 months
        singapore_ep: 21,             // 3 weeks
        uae_golden: 60,               // 2 months
        nz_skilled: 180,              // 6 months
        japan_hsp: 30,                // 1 month
        germany_blue: 90,             // 3 months
        netherlands_hsm: 90,          // 3 months
        ireland_critical: 60,         // 2 months
    };

    const days = processingDays[visaType] || 90; // default 3 months
    const expectedDate = new Date(submittedAt);
    expectedDate.setDate(expectedDate.getDate() + days);

    return expectedDate;
}

/**
 * Generate default milestones when application is submitted
 */
export function generateDefaultMilestones(
    applicationId: string,
    visaType: VisaType,
    submittedAt: Date
): Milestone[] {
    const milestones: Milestone[] = [];
    const now = new Date();

    // 1. Submission milestone (completed)
    milestones.push({
        id: `${applicationId}-submission`,
        applicationId,
        type: "SUBMISSION",
        label: "Application Submitted",
        description: "Your application has been submitted to the official portal",
        plannedDate: submittedAt,
        actualDate: submittedAt,
        createdAt: now,
        status: "COMPLETED",
        isAutoGenerated: true,
        order: 1,
    });

    // 2. Under review milestone (pending)
    const reviewDate = new Date(submittedAt);
    reviewDate.setDate(reviewDate.getDate() + 7); // typically starts review after 1 week

    milestones.push({
        id: `${applicationId}-review`,
        applicationId,
        type: "ENDORSEMENT_REVIEW",
        label: "Under Review",
        description: "Your application is being reviewed by the authorities",
        plannedDate: reviewDate,
        createdAt: now,
        status: "PENDING",
        isAutoGenerated: true,
        order: 2,
    });

    // 3. Decision milestone (pending)
    const decisionDate = calculateExpectedDecisionDate(visaType, submittedAt);

    milestones.push({
        id: `${applicationId}-decision`,
        applicationId,
        type: "DECISION",
        label: "Decision Expected",
        description: "Final decision on your application",
        plannedDate: decisionDate,
        createdAt: now,
        status: "PENDING",
        isAutoGenerated: true,
        order: 3,
    });

    // 4. Visa-specific milestones
    if (visaType === "uk_global_talent") {
        // UK Global Talent often requires endorsement first
        const endorsementDate = new Date(submittedAt);
        endorsementDate.setDate(endorsementDate.getDate() + 28); // 4 weeks for endorsement

        milestones.push({
            id: `${applicationId}-endorsement`,
            applicationId,
            type: "ENDORSEMENT_REVIEW",
            label: "Tech Nation Endorsement",
            description: "Endorsement decision from Tech Nation",
            plannedDate: endorsementDate,
            createdAt: now,
            status: "PENDING",
            isAutoGenerated: true,
            order: 2,
        });
    }

    return milestones;
}

/**
 * Generate a biometric appointment milestone
 */
export function generateBiometricMilestone(
    applicationId: string,
    appointmentDate: Date,
    location?: string
): Milestone {
    return {
        id: `${applicationId}-biometric-${Date.now()}`,
        applicationId,
        type: "BIOMETRIC_APPOINTMENT",
        label: "Biometric Appointment",
        description: "Attend biometric data collection appointment",
        plannedDate: appointmentDate,
        createdAt: new Date(),
        status: "PENDING",
        location,
        requirementsChecklist: [
            "Bring appointment confirmation letter",
            "Bring valid passport",
            "Arrive 15 minutes early",
        ],
        isAutoGenerated: false,
        order: 99, // User-created milestones go at the end
    };
}

/**
 * Generate an interview milestone
 */
export function generateInterviewMilestone(
    applicationId: string,
    interviewDate: Date,
    location?: string
): Milestone {
    return {
        id: `${applicationId}-interview-${Date.now()}`,
        applicationId,
        type: "INTERVIEW",
        label: "Interview Scheduled",
        description: "Attend visa interview",
        plannedDate: interviewDate,
        createdAt: new Date(),
        status: "PENDING",
        location,
        requirementsChecklist: [
            "Bring all original documents",
            "Bring interview confirmation",
            "Review application details",
        ],
        isAutoGenerated: false,
        order: 99,
    };
}

/**
 * Update milestone status based on current date
 */
export function updateMilestoneStatus(milestone: Milestone): Milestone {
    const now = new Date();

    // If completed, keep as completed
    if (milestone.status === "COMPLETED" || milestone.status === "CANCELLED") {
        return milestone;
    }

    // Check if overdue
    if (now > milestone.plannedDate && milestone.status !== "COMPLETED") {
        return { ...milestone, status: "OVERDUE" };
    }

    // Check if in progress (within 7 days of planned date)
    const sevenDaysBeforePlanned = new Date(milestone.plannedDate);
    sevenDaysBeforePlanned.setDate(sevenDaysBeforePlanned.getDate() - 7);

    if (now >= sevenDaysBeforePlanned && now <= milestone.plannedDate) {
        return { ...milestone, status: "IN_PROGRESS" };
    }

    return milestone;
}

/**
 * Calculate days remaining or overdue for a milestone
 */
export function getMilestoneDaysInfo(milestone: Milestone): {
    daysRemaining?: number;
    daysOverdue?: number;
    isOverdue: boolean;
} {
    const now = new Date();
    const diffTime = milestone.plannedDate.getTime() - now.getTime();
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

    if (milestone.status === "COMPLETED") {
        return { isOverdue: false };
    }

    if (diffDays < 0) {
        return {
            daysOverdue: Math.abs(diffDays),
            isOverdue: true,
        };
    }

    return {
        daysRemaining: diffDays,
        isOverdue: false,
    };
}
