import { Milestone, MilestoneType, VisaType, ApplicationLifecycleStatus } from "@/types";

export function calculateExpectedDecisionDate(
    visaType: VisaType,
    submittedAt: Date
): Date {
    const processingDays: Record<VisaType, number> = {
        uk_global_talent: 56,
        us_h1b: 90,
        us_o1: 90,
        canada_express_entry: 180,
        australia_skilled: 120,
        eu_blue_card: 90,
        singapore_ep: 21,
        uae_golden: 60,
        nz_skilled: 180,
        japan_hsp: 30,
        germany_blue: 90,
        netherlands_hsm: 90,
        ireland_critical: 60,
    };

    const days = processingDays[visaType] || 90;
    const expectedDate = new Date(submittedAt);
    expectedDate.setDate(expectedDate.getDate() + days);

    return expectedDate;
}

export function generateDefaultMilestones(
    applicationId: string,
    visaType: VisaType,
    submittedAt: Date
): Milestone[] {
    const milestones: Milestone[] = [];
    const now = new Date();

    milestones.push({
        id: `${applicationId}-submission`,
        applicationId,
        type: "SUBMISSION",
        label: "Application Submitted",
        description: "Your application has been submitted to the official portal",
        plannedDate: submittedAt,
        actualDate: submittedAt,
        createdAt: now,
        status: "COMPLETED",
        isAutoGenerated: true,
        order: 1,
    });

    const reviewDate = new Date(submittedAt);
    reviewDate.setDate(reviewDate.getDate() + 7);

    milestones.push({
        id: `${applicationId}-review`,
        applicationId,
        type: "ENDORSEMENT_REVIEW",
        label: "Under Review",
        description: "Your application is being reviewed by the authorities",
        plannedDate: reviewDate,
        createdAt: now,
        status: "PENDING",
        isAutoGenerated: true,
        order: 2,
    });

    const decisionDate = calculateExpectedDecisionDate(visaType, submittedAt);

    milestones.push({
        id: `${applicationId}-decision`,
        applicationId,
        type: "DECISION",
        label: "Decision Expected",
        description: "Final decision on your application",
        plannedDate: decisionDate,
        createdAt: now,
        status: "PENDING",
        isAutoGenerated: true,
        order: 3,
    });

    if (visaType === "uk_global_talent") {
        const endorsementDate = new Date(submittedAt);
        endorsementDate.setDate(endorsementDate.getDate() + 28);

        milestones.push({
            id: `${applicationId}-endorsement`,
            applicationId,
            type: "ENDORSEMENT_REVIEW",
            label: "Tech Nation Endorsement",
            description: "Endorsement decision from Tech Nation",
            plannedDate: endorsementDate,
            createdAt: now,
            status: "PENDING",
            isAutoGenerated: true,
            order: 2,
        });
    }

    return milestones;
}

export function generateBiometricMilestone(
    applicationId: string,
    appointmentDate: Date,
    location?: string
): Milestone {
    return {
        id: `${applicationId}-biometric-${Date.now()}`,
        applicationId,
        type: "BIOMETRIC_APPOINTMENT",
        label: "Biometric Appointment",
        description: "Attend biometric data collection appointment",
        plannedDate: appointmentDate,
        createdAt: new Date(),
        status: "PENDING",
        location,
        requirementsChecklist: [
            "Bring appointment confirmation letter",
            "Bring valid passport",
            "Arrive 15 minutes early",
        ],
        isAutoGenerated: false,
        order: 99,
    };
}

export function generateInterviewMilestone(
    applicationId: string,
    interviewDate: Date,
    location?: string
): Milestone {
    return {
        id: `${applicationId}-interview-${Date.now()}`,
        applicationId,
        type: "INTERVIEW",
        label: "Interview Scheduled",
        description: "Attend visa interview",
        plannedDate: interviewDate,
        createdAt: new Date(),
        status: "PENDING",
        location,
        requirementsChecklist: [
            "Bring all original documents",
            "Bring interview confirmation",
            "Review application details",
        ],
        isAutoGenerated: false,
        order: 99,
    };
}

export function updateMilestoneStatus(milestone: Milestone): Milestone {
    const now = new Date();

    if (milestone.status === "COMPLETED" || milestone.status === "CANCELLED") {
        return milestone;
    }

    if (now > milestone.plannedDate && milestone.status !== "COMPLETED") {
        return { ...milestone, status: "OVERDUE" };
    }

    const sevenDaysBeforePlanned = new Date(milestone.plannedDate);
    sevenDaysBeforePlanned.setDate(sevenDaysBeforePlanned.getDate() - 7);

    if (now >= sevenDaysBeforePlanned && now <= milestone.plannedDate) {
        return { ...milestone, status: "IN_PROGRESS" };
    }

    return milestone;
}

export function getMilestoneDaysInfo(milestone: Milestone): {
    daysRemaining?: number;
    daysOverdue?: number;
    isOverdue: boolean;
} {
    const now = new Date();
    const diffTime = milestone.plannedDate.getTime() - now.getTime();
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

    if (milestone.status === "COMPLETED") {
        return { isOverdue: false };
    }

    if (diffDays < 0) {
        return {
            daysOverdue: Math.abs(diffDays),
            isOverdue: true,
        };
    }

    return {
        daysRemaining: diffDays,
        isOverdue: false,
    };
}
