import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/auth";
import { MilestoneStatus } from "@/types";

export async function PUT(
    request: NextRequest,
    { params }: { params: { id: string; milestoneId: string } }
) {
    try {
        const session = await auth();

        if (!session?.user) {
            return NextResponse.json(
                { error: "Unauthorized" },
                { status: 401 }
            );
        }

        const { milestoneId } = params;
        const body = await request.json();

        const {
            status,
            actualDate,
            plannedDate,
            label,
            description,
            location,
            requirementsChecklist,
            notes,
        } = body;

        // TODO: Fetch milestone from database to verify it exists
        // const milestone = await db.milestones.findUnique({ where: { id: milestoneId } });
        // if (!milestone) {
        //     return NextResponse.json({ error: "Milestone not found" }, { status: 404 });
        // }

        // Prepare update data
        const updateData: any = {
            updatedAt: new Date(),
        };

        if (status) updateData.status = status as MilestoneStatus;
        if (actualDate) updateData.actualDate = new Date(actualDate);
        if (plannedDate) updateData.plannedDate = new Date(plannedDate);
        if (label) updateData.label = label;
        if (description !== undefined) updateData.description = description;
        if (location !== undefined) updateData.location = location;
        if (requirementsChecklist) updateData.requirementsChecklist = requirementsChecklist;
        if (notes !== undefined) updateData.notes = notes;

        // If marking as completed and no actualDate provided, set it to now
        if (status === "COMPLETED" && !actualDate && !updateData.actualDate) {
            updateData.actualDate = new Date();
        }

        // TODO: Update milestone in database
        // await db.milestones.update({ where: { id: milestoneId }, data: updateData });

        return NextResponse.json({
            success: true,
            milestone: { id: milestoneId, ...updateData },
            message: "Milestone updated successfully",
        });

    } catch (error) {
        console.error("Error updating milestone:", error);
        return NextResponse.json(
            { error: "Internal server error" },
            { status: 500 }
        );
    }
}

export async function DELETE(
    request: NextRequest,
    { params }: { params: { id: string; milestoneId: string } }
) {
    try {
        const session = await auth();

        if (!session?.user) {
            return NextResponse.json(
                { error: "Unauthorized" },
                { status: 401 }
            );
        }

        const { milestoneId } = params;

        // TODO: Fetch milestone to verify it's not auto-generated
        // const milestone = await db.milestones.findUnique({ where: { id: milestoneId } });
        // if (!milestone) {
        //     return NextResponse.json({ error: "Milestone not found" }, { status: 404 });
        // }
        // if (milestone.isAutoGenerated) {
        //     return NextResponse.json(
        //         { error: "Cannot delete auto-generated milestones" },
        //         { status: 403 }
        //     );
        // }

        // TODO: Delete milestone from database
        // await db.milestones.delete({ where: { id: milestoneId } });

        return NextResponse.json({
            success: true,
            message: "Milestone deleted successfully",
        });

    } catch (error) {
        console.error("Error deleting milestone:", error);
        return NextResponse.json(
            { error: "Internal server error" },
            { status: 500 }
        );
    }
}
